# # senha padrao do seleniumhub é :secret
services:

  storybook-webapp:
    container_name:  storybook-webapp
    build: 
      context: .
      dockerfile: dockerfile-storybook
    ports:
      - "4300:8080"
    environment:
      - ENVIRONMENT_NAME=Test
    networks:
      - storybookNetwork

  webapp:
    container_name: WebApp
    build: 
      context: .
      dockerfile: dockerfile
    ports:
      - "4200:80"
    networks:
      - storybookNetwork

networks:
  storybookNetwork:
    driver: bridge